### PR TITLE
Bug Fix for Issue #554

### LINKED ISSUE #554: Bug with Daily Quotes when user starts the app
When the app starts with the "Daily Quote" fragment displayed and the user clicks the "Don't Show Again" button, nothing happens.

### Steps to reproduce
Using Genymotion with Google Pixel 2.0 device, Android 8.0 - API 26

### Expected behaviour
When the "Don't Show Again" button is clicked, it should return to the Main Activity displaying the featured cities
### Actual behaviour
When the "Don't Show Again" button is clicked nothing happens and you need to press the 'Back' button on the Android screen to actually get to the Main Activitity screen. Demonstrated here:

### Would you like to work on the issue?
Yes, I would like to work on this issue and publish a PR containing the fix.

### PR DESCRIPTION
**Pull request by jtj9817**
## Bug fix
Fixed the bug described in #554 by properly redirecting the user to the 'Most Popular Cities' app page instead of the button not doing anything. This also has a direct effect on the settings of the user that once the 'Don't Show Again' button has been clicked, the user **will not see anymore daily quotes**.

fixes #554 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# Demonstration of bug fix

### CODE REVIEW

File: Android/app/src/main/java/io/github/project_travel_mate/utilities/DailyQuotesFragment.java [hunk 1]
```diff
@@ -171,10 +171,13 @@ private static Bitmap getScreenShot(View view) {
     }
 
     void doNotShowClicked() {
+        /*
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/utilities/DailyQuotesFragment.java]: Instead of commenting this code, just remove it.

Comment (Swati4star) [reply Android/app/src/main/java/io/github/project_travel_mate/utilities/DailyQuotesFragment.java]: Well, did you check why the code was not going inside this if?
which condition was not getting satisfied?

**Comment by Swati4star** [comment]
This looks good 👍
