### PR TITLE
Fix #410, Fixed the bug for app crash when auto rotated on home screen

### LINKED ISSUE #410: [BUG] App crashes in Main Screen on Rotation
### Steps to reproduce
- Main Screen i.e (Cities grid screen)
- Rotate
- App Crash

### Expected behaviour
- App should not crash

### Actual behaviour
- App Crashes

### Error Logs
```
08-05 09:42:59.649 7660-7660/io.github.project_travel_mate E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.project_travel_mate, PID: 7660
    java.lang.IllegalStateException: Fragment CityFragment{9219c7} not attached to a context.
        at android.support.v4.app.Fragment.requireContext(Fragment.java:614)
        at android.support.v4.app.Fragment.getResources(Fragment.java:678)
        at android.support.v4.app.Fragment.getString(Fragment.java:700)
        at io.github.project_travel_mate.destinations.CityFragment$3.lambda$onResponse$2$CityFragment$3(CityFragment.java:234)
        at io.github.project_travel_mate.destinations.CityFragment$3$$Lambda$1.run(Unknown Source:20)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### PR DESCRIPTION
**Pull request by anirudh8860**
# Description

Fixed the bug for app crash when auto-rotated on home screen

Fixes #(issue)
Fixes app crash when rotated on screen after login.

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

It has been tested on 3 emulators and on 5 different devices:

1. Redmi 3s Prime
2. Nokia 7 Plus
3. One Plus 3T
4. One Plus 5
5. Google Pixel XL

### CODE REVIEW

**Comment by Swati4star** [comment]
@anirudh8860 Fix the merge conflicts

File: Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java [hunk 1]
```diff
@@ -75,6 +76,7 @@ public static CityFragment newInstance() {
     public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container,
                              Bundle savedInstanceState) {
         View view = inflater.inflate(R.layout.fragment_citylist, container, false);
+        mCityContext = getActivity().getApplicationContext();
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java]: We already have mActivity. Why aren't you using that?

File: Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java [hunk 2]
```diff
@@ -231,8 +233,8 @@ public void onResponse(Call call, final Response response) {
                                         ar.getJSONObject(i).optString("image"),
                                         ar.getJSONObject(i).getString("city_name"),
                                         ar.getJSONObject(i).getInt("facts_count"),
-                                        getString(R.string.interest_know_more), getString(R.string.interest_weather),
-                                        getString(R.string.interest_fun_facts), getString(R.string.interest_trends)));
+                                        mCityContext.getString(R.string.interest_know_more), mCityContext.getString(R.string.interest_weather),
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java]: You can use mActivity only here. No need to create new variable.

Comment (anirudh8860) [reply Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java]: I created it because you need to fetch the context from the view of fragment. That is why crash was occuring.

Comment (Swati4star) [reply Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java]: Use mActivity. mActivity is assigned at the time of attaching. That's the correct way to get context. getActivity() can cause crash.

**Comment by Swati4star** [comment]
The merge conflicts are still here

File: Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java (hunk 2 above)
Comment (anirudh8860) [reply Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java]: Have made those changes. Please check.

**Comment by Swati4star** [comment]
Check line https://travis-ci.org/project-travel-mate/Travel-Mate/builds/413945608#L2512 
line 2512 & 2513

The exact error is mentioned (line length > 120 chars)

**Comment by anirudh8860** [comment]
When will this be pushed in official repo?

**Comment by anirudh8860** [comment]
hey @Swati4star, can you close this issue?

**Comment by Swati4star** [comment]
You should mention the issue number in the description. It closes automatically then.
