### PR TITLE
The compass (in utilities) doesn't work for devices that don't have m…

### LINKED ISSUE #457: The compass (in utilities) doesn't work for devices that don't have magnetic sensor
Show an alert on opening utilities in these devices

Ref:
https://stackoverflow.com/questions/9027133/how-to-know-if-a-sensor-is-present-on-my-android-device

### PR DESCRIPTION
**Pull request by santoshhiremani**
…agnetic sensor #457

Fixes #457 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

File: Android/app/src/main/java/io/github/project_travel_mate/utilities/CompassActivity.java [hunk 1]
```diff
@@ -29,9 +35,35 @@ protected void onCreate(@Nullable Bundle savedInstanceState) {
...
+    /**
+     * Check AccelerometerSensor in device
+     **/
+    private void getAccelerometerSensor() {
+        PackageManager mManager = getPackageManager();
+        boolean hasAccelerometer = mManager.hasSystemFeature(PackageManager.FEATURE_SENSOR_ACCELEROMETER);
+        boolean hasMagneticSensor = mManager.hasSystemFeature(PackageManager.FEATURE_SENSOR_COMPASS);
+        if (!hasAccelerometer || !hasMagneticSensor) {
+            AlertDialog alertDialog = new AlertDialog.Builder(CompassActivity.this).create();
+            alertDialog.setTitle("Info");
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/utilities/CompassActivity.java]: Please don't add contant strings in java code. Add them to strings.xml file & use those here

File: Android/app/src/main/java/io/github/project_travel_mate/utilities/CompassActivity.java [hunk 2]
```diff
@@ -29,9 +40,35 @@ protected void onCreate(@Nullable Bundle savedInstanceState) {
...
+    /**
+     * Check AccelerometerSensor in device
+     **/
+    private void getAccelerometerSensor() {
+        PackageManager mManager = getPackageManager();
+        boolean hasAccelerometer = mManager.hasSystemFeature(PackageManager.FEATURE_SENSOR_ACCELEROMETER);
+        boolean hasMagneticSensor = mManager.hasSystemFeature(PackageManager.FEATURE_SENSOR_COMPASS);
+        if (!hasAccelerometer || !hasMagneticSensor) {
+            AlertDialog alertDialog = new AlertDialog.Builder(CompassActivity.this).create();
+            alertDialog.setTitle(COMPASS_DIALOG_HEADER);
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/utilities/CompassActivity.java]: add strings to strings.xml, These are not constants.
