### PR TITLE
#697 - fix toast message is showing when navigating back to login

### LINKED ISSUE #697: toast message is showing when navigating back to login
Screenshot_1566124474

**Current Behaviour**

Snackbar is showing a message "your password has been reset. Login with the new password" when moving back to login screen from forgot password screen. (I have not done password reset but still it shows this message).

**Steps to reproduce**

1. Click on Forgot password 
2. Forgot password screen will be opened 
3. Then click on back to login
4. It shows the snackbar with a message

**Expected Behaviour**

It should show the message on forgot password screen only when password is actually changed in the backend.

### PR DESCRIPTION
**Pull request by dekzitfz**
## Description

add checking before show toast message "your password has been reset. Login with the new password" when back to login from reset password ui

Fixes #697 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

File: Android/app/src/main/java/io/github/project_travel_mate/login/LoginView.java [hunk 1]
```diff
@@ -24,7 +24,7 @@
 
     void openSignUp();
 
-    void openLogin();
+    void openLogin(boolean isPassReseted);
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/login/LoginView.java]: change this variable name to "showToastMessage"

Comment (dekzitfz) [reply Android/app/src/main/java/io/github/project_travel_mate/login/LoginView.java]: done, please re check it
