### PR TITLE
trip name can now be edited

### LINKED ISSUE #198: Allow users to update trip name
Add an option to update trip name

### Steps to reproduce
- click on the navigation drawer. Go to `My Trips`
- Click on any trip

### What to do?
- Add a pencil icon by the side of trip name.
- On clicking the pencil icon, the trip name should become editable.
- Allow user to edit it (For reference: check user profile page; user name is editable there)

### Endpoint to use
The information is given in https://github.com/project-travel-mate/server/issues/58

### PR DESCRIPTION
**Pull request by aayushinigam**
Implemented feature to update trip name.

# Description
screenshot_20180711-120704
Fixes #198 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?
Ran Successfully on an android device.

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

File: Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java [hunk 1]
```diff
@@ -120,6 +127,31 @@ protected void onCreate(Bundle savedInstanceState) {
...
+                    tripName.setCursorVisible(true);
+                    tripName.requestFocus();
+                    InputMethodManager inputMethodManager = (InputMethodManager)
+                            getSystemService(Context.INPUT_METHOD_SERVICE);
+                    Objects.requireNonNull(inputMethodManager)
+                            .showSoftInput(tripName, InputMethodManager.SHOW_IMPLICIT);
+                    mIsTripNameEdited = true;
+                } else {
+                    //clicking edit trip after editing the trip name
+                    editTrip.setImageDrawable(getResources().getDrawable(R.drawable.ic_edit_black_24dp));
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java]: add a check for empty trip name
