### PR TITLE
Shopping page shows no internet connection error in case of no results #291

### LINKED ISSUE #195: Show appropriate animations on screens when there are no results
When we get no results from the API due to any reason ( there are actually no results, server error, internet connection), we just show a snackbar with some appropriate message. Replace, the snackbar with proper animations.

### Which screens are to be added with this layout?
- `City info` (opens up on clicking any city)
- `Hotel booking`
- `Online shopping`
- `Trip info` (opens up on clicking any trip)
- `Profile` 

### What to do?
- Checkout https://github.com/project-travel-mate/Travel-Mate/blob/1dac4f949697f2766c923a16eb0eb89cd0386286/Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripsFragment.java
We have functions for `networkError` `noResults`. These functions show approriate animations. Add these functions & `animationView` to above mentioned screens & show them when required.

### LINKED ISSUE #291: Shopping page shows no internet connection error in case of no results
### Steps to reproduce
- Select `Travel` -> `Online Shopping`
- Search for something like `blaaah`

### Expected behaviour
The no results animation should be displayed

### Actual behaviour
The screen shows no internet connection animation
screen shot 2018-07-17 at 8 06 32 pm

### PR DESCRIPTION
**Pull request by syedjahangirpeeran**
Fixes #291.

### CODE REVIEW

**Comment by Swati4star** [comment]
@syedjahangirpeeran Screenshot

File: Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingCurrentCityActivity.java [hunk 1]
```diff
@@ -195,14 +198,15 @@ public void onResponse(Call call, final Response response) {
                                 Utils.hideKeyboard(ShoppingCurrentCityActivity.this);
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingCurrentCityActivity.java]: noResults should be called here

File: Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingCurrentCityActivity.java [hunk 2]
```diff
@@ -195,14 +198,15 @@ public void onResponse(Call call, final Response response) {
...
+                            layout.setVisibility(View.VISIBLE);
                             textView.setVisibility(View.GONE);
                             lv.setAdapter(new ShoppingAdapter(ShoppingCurrentCityActivity.this, feedItems));
                         } catch (JSONException | IOException e) {
                             e.printStackTrace();
                             networkError();
                         }
                     } else {
-                        networkError();
+                        noResults();
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingCurrentCityActivity.java]: The code will reach here in case of network error only.

**Comment by syedjahangirpeeran** [comment]
screenshot_20180718-201944

**Comment by Swati4star** [comment]
Isn't this a fix for https://github.com/project-travel-mate/Travel-Mate/issues/291 ?

**Comment by syedjahangirpeeran** [comment]
My bad it is for #291 will change the description.

File: Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingCurrentCityActivity.java (hunk 2 above)
Comment (syedjahangirpeeran) [reply Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingCurrentCityActivity.java]: No I tested it. It's functioning perfectly. You can test it.
