### PR TITLE
Infinite scrolling in Fun facts view #171

### LINKED ISSUE #171: Infinite scrolling in Fun facts view
Add infinite scrolling in the fun facts view for a city

### Steps to reproduce
- Go to home page `destinations`
- Swipe the `Delhi` item (all cities don't have fun facts right now. But Delhi has, so you can try on Delhi)
- Click on fun facts
- A fun facts view open ups.
- You can swipe left to show other facts

### Expected behaviour
- Add infinite scrolling (When the last item is reached, on swiping next, show the first item again)

### Actual behaviour
- When the facts get over, We can't swipe anymore

### PR DESCRIPTION
**Pull request by syedjahangirpeeran**
Fixes #171.

### CODE REVIEW

File: Android/app/src/main/java/io/github/project_travel_mate/destinations/funfacts/FunFactsActivity.java [hunk 1]
```diff
@@ -42,6 +44,10 @@
     private City mCity;
     private String mToken;
     private Handler mHandler;
+    Boolean isFirstVisitEnd= true;
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/destinations/funfacts/FunFactsActivity.java]: add space before =
The test will fail.

File: Android/app/src/main/java/io/github/project_travel_mate/destinations/funfacts/FunFactsActivity.java [hunk 2]
```diff
@@ -90,10 +96,41 @@ public void setupViewPager(final ArrayList<FunFact> factsArray) {
                 FunFact fact = new FunFact(mCity.getNickname(),
                         factsArray.get(i).getImage(),
                         factsArray.get(i).getText(), factsArray.get(i).getSource(), factsArray.get(i).getSourceURL());
+                Log.e("PRINT",factsArray.get(i).getText());
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/destinations/funfacts/FunFactsActivity.java]: make it Log.d or remove it

**Comment by Swati4star** [comment]
@syedjahangirpeeran Checks
