### PR TITLE
removed bug from friends' list

### LINKED ISSUE #324: My Friends screen does not show all the freinds
### Steps to reproduce
1. Go To `My Friends` in navigation drawer

### Expected behaviour
All friends should be shown.

### Actual behaviour
Among all the friends, one friend is missed.

### Would you like to work on the issue?
Yes.

### PR DESCRIPTION
**Pull request by aayushinigam**
# Description

Fixes #324 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

File: Android/app/src/main/java/io/github/project_travel_mate/MyFriendsFragment.java [hunk 1]
```diff
@@ -113,7 +113,7 @@ public void onResponse(Call call, final Response response) throws IOException {
                                 return;
                             }
 
-                            for (int i = 0; i < arr.length() - 1; i++) {
+                            for (int i = 1; i < arr.length(); i++) {
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/MyFriendsFragment.java]: Make it start from 0 only. I have created an issue in the server to don't include friend's own info(https://github.com/project-travel-mate/server/issues/100)
