### PR TITLE
Save most popular cities offline #188

### LINKED ISSUE #188: Save most popular cities offline
Every time, user visit `Destinations` page, an API call is made. This experience is not good.

### Steps to reproduce
- Go to the navigation drawer. Click `Destinations`
- Go to some other fragment. Come to `Destinations` again.
- Again the API call is made.

### Expected behaviour
The information should be saved locally.

### Actual behaviour
API call is made every time

### What to do?
- Create a local database (using `Room persistence library`)
- If the database is empty, show the loader & fetch response & fill the db. (Set an expiration time. 24 hours for the database, after which it is deleted & has to be filled again)
- If the database has information, use that to fill the layout on `Destinations` page

### PR DESCRIPTION
**Pull request by santoshhiremani**
## Description

roomVersion = "1.0.0" has changed to 1.0.0-beta2 since there was gradle issue. 

Fixes #188

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

File: Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java [hunk 1]
```diff
@@ -86,6 +95,8 @@ public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container,
 
         SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(mActivity);
         mToken = sharedPreferences.getString(USER_TOKEN, null);
+        mSharedPreferences = PreferenceManager.getDefaultSharedPreferences(getActivity());
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java]: Don;t use getActivity
Use mActivity

File: Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java [hunk 2]
```diff
@@ -105,10 +116,57 @@ public boolean onQueryTextChange(String newText) {
...
+                City city = (City) lv.getAdapter().getItem(position);
+                Intent intent = FinalCityInfoActivity.getStartIntent(mActivity, city);
+                startActivity(intent);
+            });
+        }
         return view;
     }
 
+    /*
+     * Check cached cities with expiration time 24 hours
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java]: Add javadoc style comments to the newly added funtions (that's what we are following)
It explains about parameters & return values too

File: Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java (hunk 1 above)
Comment (santoshhiremani) [reply Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java]: ok
