### PR TITLE
Fixes #703 fixes trip future date issue in AddNewTripActivity.java

### LINKED ISSUE #703: Future trip date not selected of current month.
## Current Behaviour

When I selected future date of this month like this.

after_estimote

after clicking ok button. It gives error massage on snakeBar like this.

snackbar

But when I selected any date of next month. It works fine

## Expectec Behaviour:
- When I select current date it shows a time dialog
- When I select current date and current time it show a error that select future date or future time
- When I select future date of this month or any other month it book my trip

### PR DESCRIPTION
**Pull request by AminullahTajMuhammad**
## Description

When I selected a future date of the current month on add new trip screen it gives error snack bar. But when I selected next month date it works fine. So I have fixed that when we selected any future date of any month. It works fine.

Fixes #703

## Type of change
Just put an x in the [] which are valid.
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [X] `./gradlew assembleDebug assembleRelease`
- [X] `./gradlew checkstyle`

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
@AminullahTajMuhammad Travis checks are failing. Please check.

File: Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java [hunk 1]
```diff
@@ -300,19 +299,31 @@ private void networkError() {
     @Override
     public void onDateSet(DatePicker view, int year, int month, int dayOfMonth) {
         String currentDateString = new SimpleDateFormat("dd-MM-yyyy", Locale.getDefault()).format(new Date());
-        int currentDay = Integer.parseInt(currentDateString.split("-")[0]);
-        int currentMonth = Integer.parseInt(currentDateString.split("-")[1]);
-        int currentYear = Integer.parseInt(currentDateString.split("-")[2]);
+//        int currentDay = Integer.parseInt(currentDateString.split("-")[0]);
```
Comment (Swati4star) [inline Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java]: don't comment. remove these.

**Comment by AminullahTajMuhammad** [comment]
@Swati4star fixed changes
